#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

fpath=(/usr/local/share/zsh/site-functions $fpath)

path=( /usr/local/bin $path )

[ -f ~/.kerlrc ] \
    && source ~/.kerlrc \
    && [ ! -z "$KERL_INSTALL" ] \
    && [ ! -z "$KERL_INSTALL_DIR" ] \
    && . ${KERL_INSTALL_DIR}/${KERL_INSTALL}/activate
# Problem: when invoking commands from e.g. vim with ':!cmd' the shell in which
# it is executed only loads this file, not zshrc. Which means it uses the standard
# system erlang installation not the kerl-controlled one.
# A way to load the kerl module here would help, but may be totally wrong.
path=( ~/kex/elixir-1.0.2/bin $path)
