#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

module_path=($module_path /usr/local/lib/zpython)

zmodload zsh/zpython

_POWERLINE_DIR=$(python -c "import pkg_resources; dist = pkg_resources.get_distribution(\"powerline-status\"); print dist.location")
if [ -n "$_POWERLINE_DIR" -a -d $_POWERLINE_DIR ]; then
    . $_POWERLINE_DIR/powerline/bindings/zsh/powerline.zsh
    PREZTO_PROMPT="off"
    VIRTUAL_ENV_DISABLE_PROMPT="on"
else
    PREZTO_PROMPT="on"
fi
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
path=(~/bin $path)
path=($path /usr/local/opt/go/libexec/bin)

export EDITOR="nvim"

test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh

# added by travis gem
[ -f /Users/sanmiguel/.travis/travis.sh ] && source /Users/sanmiguel/.travis/travis.sh
